package com.backend.domicare.exception;


public enum ExceptionConstants {

	INVALID_AUTHENTICATED(102, "INVALID_AUTHENTICATED"),

	INTERNAL_SERVER_ERROR(103, "INTERNAL_SERVER_ERROR"),

	INVALID_SYNTAX(104, "INVALID_SYNTAX"),

	EMAIL_ALREADY_EXISTS(108, "EMAIL_ALREADY_EXISTS"),
	
	NOT_FOUND_FILE(109, "FILE_NOT_FOUND"),

	UNAUTHORIZED(113,"UNAUTHORIZED"),

	ADMIN_UNAUTHORIZED(114,"ADMIN_UNAUTHORIZED"),

	UNAUTHORIZED_ADMIN_DELETE_OTHER_ADMINS(113,"UNAUTHORIZED_ADMIN_DELETE_OTHER_ADMINS"),

	ORDER_ID_NOT_EXISTS(211, "ORDER_ID_NOT_EXISTS"),

    INVALID_REFRESH_TOKEN(116, "INVALID_REFRESH_TOKEN"),

    NOT_FOUND_USER_ID( 112, "USER_NOT_FOUND"),

    NOT_FOUND_EMAIL( 117, "EMAIL_NOT_FOUND"),

    EMAIL_NOT_COMFIRMED(118, "EMAIL_NOT_COMFIRMED"),

    BAD_CREDENTIALS(119, "BAD_CREDENTIALS"),

	INVALID_EMAIL(120, "INVALID_EMAIL"),

	PRODUCT_NAME_ALREADY_EXISTS(121, "PRODUCT_NAME_ALREADY_EXISTS"),
	
	NOT_FOUND_PRODUCT_ID(122, "NOT_FOUND_PRODUCT_ID"),

	CATEGORY_ALREADY_EXISTS(124, "CATEGORY_ALREADY_EXISTS"),

	CATEGORY_NOT_FOUND(125, "CATEGORY_NOT_FOUND"),

	PRODUCT_NOT_IN_CATEGORY(126, "PRODUCT_NOT_IN_CATEGORY"),

	ROLE_ALREADY_EXISTS(127, "ROLE_ALREADY_EXISTS"),

	NOT_FOUND_ROLE(128, "NOT_FOUND_ROLE"),

	ALREADY_REVIEWED(129, "ALREADY_REVIEWED"),

	URL_ALREADY_EXISTS(130, "URL_ALREADY_EXISTS"),

	BOOKING_NOT_FOUND(131, "BOOKING_NOT_FOUND"),

	BOOKING_STATUS_INVALID(132, "BOOKING_STATUS_INVALID"),;


	private final int code;
	private final String messageName;

	ExceptionConstants(int code, String messageName) {
		this.code = code;
		this.messageName = messageName;
	}

	public int getCode() {
		return code;
	}

	public String getMessageName() {
		return messageName;
	}
}
