version: '3.8'

services:
  domicare:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    env_file:
      - .env
    volumes:
      - ./src/main/resources:/app/resources
    networks:
      - domicare-network

networks:
  domicare-network:
    driver: bridge

