version: '3.8'

services:
  domicare:
    build:
      context: .
      dockerfile: Dockerfile
      # Add platform specification
      platforms:
        - linux/amd64
        - linux/arm64
    image: trunganh0106/domicare-web
    ports:
      - "8080:8080"
    networks:
      - domicare-network

networks:
  domicare-network:
    driver: bridge
