version: '3.8'

services:
  domicare:
    build:
      context: .
      dockerfile: Dockerfile
    image: domicare/backend
    ports:
      - "8080:8080"
    networks:
      - domicare-network

networks:
  domicare-network:
    driver: bridge
