import logo from './LogoDomicare (2).svg'
import logoSecond from './Logo domicare (2).png'
import loginPic from './loginPic.jpg'
import pic1 from './pic1.png'
import pic2 from './pic2.png'
import pic3 from './pic3.png'
import pic4 from './pic4.png'
import pic5 from './pic5.png'
import pic6 from './pic6.png'
import pic7 from './pic7.jpg'
import pic8 from './pic8.jpg'
import pic9 from './pic9.png'
import pic10 from './pic10.png'
import Person from './Persion.png'

export { logo, loginPic, logoSecond, pic1, pic2, pic3, pic4, pic5, pic10, pic6, pic7, pic8, pic9, Person }
